// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title PassportProofVerifier
 * @dev Mock verifier contract for ZK passport proofs
 * In production, this would be generated by circom/snarkjs
 */
contract PassportProofVerifier {
    struct Proof {
        uint[2] a;
        uint[2][2] b;
        uint[2] c;
    }
    
    /**
     * @dev Verify ZK proof (mock implementation)
     * @param proof The ZK proof
     * @param publicSignals The public outputs: [isAdult, isIndian, hasExpired]
     * @return true if proof is valid
     */
    function verifyProof(
        Proof memory proof,
        uint[3] memory publicSignals
    ) public pure returns (bool) {
        // Mock verification - in production this would verify the actual ZK proof
        // For demonstration, we accept any proof with reasonable public signals
        
        // Basic validation of public signals
        require(publicSignals[0] <= 1, "isAdult must be 0 or 1");
        require(publicSignals[1] <= 1, "isIndian must be 0 or 1"); 
        require(publicSignals[2] <= 1, "hasExpired must be 0 or 1");
        
        // Mock proof validation (always returns true for demo)
        return true;
    }
}

/**
 * @title ProfileManager
 * @dev Main contract for managing verified passport profiles
 */
contract ProfileManager {
    PassportProofVerifier public immutable verifier;
    
    struct Profile {
        bool isAdult;
        bool isIndian;
        bool hasExpired;
        uint256 verifiedAt;
        string ensName;
        bool exists;
    }
    
    // Address to profile mapping
    mapping(address => Profile) public profiles;
    
    // ENS name to address mapping
    mapping(string => address) public ensToAddress;
    
    // Events
    event ProfileVerified(
        address indexed user,
        bool isAdult,
        bool isIndian, 
        bool hasExpired,
        string ensName
    );
    
    event ENSNameSet(address indexed user, string ensName);
    
    constructor(address _verifier) {
        verifier = PassportProofVerifier(_verifier);
    }
    
    /**
     * @dev Submit ZK proof to verify passport data
     * @param proof The ZK proof
     * @param publicSignals [isAdult, isIndian, hasExpired]
     * @param ensName ENS name to associate with profile
     */
    function verifyPassport(
        PassportProofVerifier.Proof memory proof,
        uint[3] memory publicSignals,
        string memory ensName
    ) external {
        require(verifier.verifyProof(proof, publicSignals), "Invalid proof");
        require(bytes(ensName).length > 0, "ENS name required");
        
        // Store verified profile
        profiles[msg.sender] = Profile({
            isAdult: publicSignals[0] == 1,
            isIndian: publicSignals[1] == 1,
            hasExpired: publicSignals[2] == 1,
            verifiedAt: block.timestamp,
            ensName: ensName,
            exists: true
        });
        
        // Map ENS name to address
        ensToAddress[ensName] = msg.sender;
        
        emit ProfileVerified(
            msg.sender,
            publicSignals[0] == 1,
            publicSignals[1] == 1,
            publicSignals[2] == 1,
            ensName
        );
        
        emit ENSNameSet(msg.sender, ensName);
    }
    
    /**
     * @dev Get profile by address
     */
    function getProfile(address user) external view returns (Profile memory) {
        require(profiles[user].exists, "Profile not found");
        return profiles[user];
    }
    
    /**
     * @dev Get profile by ENS name
     */
    function getProfileByENS(string memory ensName) external view returns (Profile memory) {
        address user = ensToAddress[ensName];
        require(user != address(0), "ENS name not found");
        require(profiles[user].exists, "Profile not found");
        return profiles[user];
    }
    
    /**
     * @dev Check if user meets age requirement
     */
    function isUserAdult(address user) external view returns (bool) {
        require(profiles[user].exists, "Profile not found");
        require(!profiles[user].hasExpired, "Document expired");
        return profiles[user].isAdult;
    }
    
    /**
     * @dev Check if user is Indian citizen
     */
    function isUserIndian(address user) external view returns (bool) {
        require(profiles[user].exists, "Profile not found");
        require(!profiles[user].hasExpired, "Document expired");
        return profiles[user].isIndian;
    }
    
    /**
     * @dev Update ENS name for existing profile
     */
    function updateENSName(string memory newENSName) external {
        require(profiles[msg.sender].exists, "Profile not found");
        require(bytes(newENSName).length > 0, "ENS name required");
        
        // Remove old ENS mapping
        string memory oldENS = profiles[msg.sender].ensName;
        if (bytes(oldENS).length > 0) {
            delete ensToAddress[oldENS];
        }
        
        // Set new ENS mapping
        profiles[msg.sender].ensName = newENSName;
        ensToAddress[newENSName] = msg.sender;
        
        emit ENSNameSet(msg.sender, newENSName);
    }
}